export const INDUSTRIES = [
  "Demolition & Land Clearing",
  "Construction & Trades",
  "Restoration & Remediation",
  "Insurance & Claims Adjusting",
  "Agriculture & Farming",
  "Food Processing & Manufacturing",
  "Restaurants & Food Services",
  "Retail & E-commerce",
  "Healthcare & Wellness",
  "Real Estate & Property",
  "Legal Services",
  "Accounting & Finance",
  "Automotive & Equipment",
  "Logistics & Transportation",
  "Renewable Energy",
  "Tourism & Hospitality",
  "Education & Childcare",
  "Beauty & Personal Care",
  "Non-profit & Community Services",
  "IT & Technology",
  "Marketing & Advertising",
];
